on:
  push:
    branches: [main, staging, trying]
  pull_request:

name: Run CI

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: thumbv7em-none-eabihf
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2.2.0
    - name: Install Dependencies
      run: |
        sudo apt update
        cargo install cargo-binutils
        rustup component add llvm-tools-preview clippy rustfmt
    - name: Check
      run: cargo check --target thumbv7em-none-eabihf
    - name: Clippy
      run: cargo clippy --target thumbv7em-none-eabihf
    - name: Format
      run: cargo fmt --all -- --check
    - name: Run cargo doc
      run: cargo doc --all-features --locked
      env:
        RUSTDOCFLAGS: '-D warnings'